export const ERROR_CODE_DUPLICATE_KEY = "23505";
export const ACCESS_TOKEN_DURATION = "15m";
export const REFRESH_TOKEN_DURATION = "7d";

const UNIX_FIFTEEN_MINUTES = 15 * 60 * 1000;
const UNIX_SEVEN_DAYS = 7 * 24 * 60 * 60 * 1000;
export const SESSION_ACCESS_TOKEN_DURATION = UNIX_FIFTEEN_MINUTES;
export const SESSION_REFRESH_TOKEN_DURATION = UNIX_SEVEN_DAYS;
